#Author: Aditya Shibrady Padmanabha
#AXS142431

library(rpart)
data(kyphosis)
ctree <- rpart(Kyphosis~., data = kyphosis, method = "class", parms = list(split = 'information'), minsplit = 1, minbucket = 1)
printcp(ctree)
plot(ctree)
text(ctree,use.n = TRUE)
print(ctree)
ctree$variable.importance
jpeg("class.jpg")
par(mar = rep(0.1, 4))
plot(ctree,uniform=TRUE,main="Classification Tree")
text(ctree,use.n=TRUE, all=TRUE, cex=.8)
dev.off()
summary(ctree)
printcp(ctree)
treepruned <- prune(ctree,cp=0.010000)
jpeg("prune.jpg")
plot(treepruned,uniform=TRUE,main="Pruned Tree")
text(treepruned,use.n=TRUE, all=TRUE, cex=.8)
dev.off()
nrow(kyphosis)
train80 <- sample(nrow(kyphosis),size =65 )
train_s80 <- kyphosis[train80,]
test_s80 <- kyphosis[-train80,]
treetrain <- rpart(Kyphosis~., data = train_s80, method = "class", parms = list(split = 'information'), minsplit = 1, minbucket = 1)
print(treetrain)
treetrain$variable.importance
jpeg("train80.jpg")
par(mar = rep(0.1, 4))
plot(treetrain,uniform=TRUE,main="Classification Tree for 80% split")
text(treetrain,use.n=TRUE, all=TRUE, cex=.8)
dev.off()
summary(treetrain)
printcp(treetrain)
trainprune80 <- prune(treetrain,cp=0.010000)
jpeg("trainpurne80.jpg")
dev.off()
plot(trainprune80,uniform=TRUE,main="Pruned Tree for 80% split")
text(trainprune80,use.n=TRUE, all=TRUE, cex=.8)
dev.off()
predict80 <- predict(treetrain,test_s80,type = "class")
print(predict80)
accuracy<- table(predict80,test_s80$Kyphosis)
sum(diag(accuracy))/sum(accuracy) *100
training90 <- sample(nrow(kyphosis),size =73 )
training_s90 <- kyphosis[training90,]
test_s90 <- kyphosis[-training90,]
traintree90 <- rpart(Kyphosis~., data = training_s90, method = "class", parms = list(split = 'information'), minsplit = 1, minbucket = 1)
print(traintree90)
traintree90$variable.importance
jpeg("train90.jpg")
par(mar = rep(0.1, 4))
plot(traintree90,uniform=TRUE,main="Classification Tree for 90% split")
text(traintree90,use.n=TRUE, all=TRUE, cex=.8)
dev.off()
summary(traintree90)
printcp(traintree90)
trainprune90 <- prune(traintree90,cp=0.010000)
jpeg("trainpurne90.jpg")
plot(trainprune90,uniform=TRUE,main="Pruned Tree for 90% split ")
text(trainprune90,use.n=TRUE, all=TRUE, cex=.8)
dev.off()
predict90 <- predict(traintree90,test_s90,type = "class")
print(predict90)
accuracy<- table(predict90,test_s90$Kyphosis)
sum(diag(accuracy))/sum(accuracy) *100
